### PR TITLE
Expose access to GetPropertyChangedSignal

### LINKED ISSUE #28: Expose GetPropertyChangedSignal declaratively
Right now, you can connect to the `Changed` event in Roact easily with `Roact.Event.Changed`, but using `GetPropertyChangedSignal(name)` on a specific property is much more performant and is much cleaner.

Roact makes that painful right now -- the only way right now is to connect in `didMount` and disconnect in `willUnmount`, typical for wrappers around APIs like this.

I think we can make Roact support `GetPropertyChangedSignal` as a first-class citizen for events.

### PR DESCRIPTION
**Pull request by AmaranthineCodices**
Allows access to property change events using GetPropertyChangedSignal via `Roact.Change.[EventName]`. This fixes #28.

This will behave like other events; one connection per object, etc.

Note that the vast majority of this is **not unit tested**. Lemur doesn't implement GetPropertyChangedSignal x.x

Example usage:

```lua
local Roact = require(game.ReplicatedStorage.Roact)

local test = Roact.createElement("ScreenGui", {}, {
	Roact.createElement("TextBox", {
		Position = UDim2.new(0.5, 0, 0.5, 0),
		Size = UDim2.new(0, 200, 0, 40),
		[Roact.Change.Text] = function(rbx)
			print("text changed to", rbx.Text)
		end,
		Font = "SourceSans",
		TextSize = 18,
	})
})

Roact.reify(test, game.Players.LocalPlayer:WaitForChild("PlayerGui"))
```

### CODE REVIEW

**Comment by LPGhatguy** [comment]
Ergh. Maybe we should implement support for `GetPropertyChanged` signal before this lands. I definitely want to improve test coverage as much as possible, which will probably involve rewriting the reconciler tests.

We didn't have test coverage metrics for Lua code when the majority of the Roact tests were written! D:

**Comment by AmaranthineCodices** [comment]
I would love to get support for `GetPropertyChangedSignal` in Lemur. I'm not familiar enough with Lemur's codebase and how it does events to implement it though :(

**Comment by LPGhatguy** [comment]
Stuff is in Lemur!

**Comment by AmaranthineCodices** [comment]
Cool! I'll try to get to this sometime this weekend.

**Comment by AmaranthineCodices** [comment]
this was not intended to drag in 27 commits >.<

**Pull request closed without merging**
